### ISSUE TITLE
Load AsyncProfiler with ap-loader

### ISSUE THREAD

**Issue by cyriltovena** [grafana/JPProf#19]
We should replace our custom integration of AsyncProfiler with https://github.com/parttimenerd/ap-loader so that we don't have to worry about the platform and architecture.

**Comment by parttimenerd** [comment]
I'm happy to to help if there are any issues :)

**Comment by parttimenerd** [comment]
I looked into it: I forgot to integrate the converter as a proper Java API (because I have to move the classes into a new package, as I don't want the converter classes in the default package).

**Comment by cyriltovena** [comment]
I think it's fine, we can copy the converter code, it had a bug anyway.

**Comment by parttimenerd** [comment]
Or I could integrate it properly

**Comment by parttimenerd** [comment]
I implemented a draft version of the former in https://github.com/parttimenerd/ap-loader/commit/dea409343495e599c2cfc0e6c1e26786d6c9d157 (in a separate branch).

**Comment by parttimenerd** [comment]
It's an PR at https://github.com/parttimenerd/ap-loader/pull/1

**Comment by parttimenerd** [comment]
Any thoughts on my PR?
